<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ2Ra6df\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ2Ra6df/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ2Ra6df.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ2Ra6df\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZ2Ra6df\App_KernelDevDebugContainer([
    'container.build_hash' => 'Z2Ra6df',
    'container.build_id' => '2aa4bb98',
    'container.build_time' => 1651758764,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ2Ra6df');
