<?php

namespace ContainerZ2Ra6df;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ApiService' shared autowired service.
     *
     * @return \App\Service\ApiService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/ApiService.php';

        return $container->privates['App\\Service\\ApiService'] = new \App\Service\ApiService(($container->services['doctrine.dbal.default_connection'] ?? $container->getDoctrine_Dbal_DefaultConnectionService()));
    }
}
